name: 'QA'

on:
  pull_request:
  push:
  schedule:
    - cron: '0 8 * * 1' # At 08:00 on Monday

env:
  php-tools: 'composer:v2'

jobs:
  cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer cs

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer phpstan
